variable "environment" {
  description = "The environment for the deployment (e.g., dev, staging, prod)"
  type        = string
}

variable "app_id" {
  description = "Name which identifies the deployed app"
  type        = string
}

variable "region" {
  description = "The AWS region to deploy resources"
  type        = string
}

variable "cloudfront_domain_name" {
  description = "The domain name for CloudFront distribution"
  type        = string
}

#-------------- File uploader variables -----------------------------------------------
# START
variable "api_file_upload_domain_name" {
  description = "The domain name for the API to get pre-signed file upload URLs"
  type        = string
}

variable "uploads_bucket_name" {
  description = "The name of the S3 bucket for file uploads"
  type        = string
  default     = "uploads-bucket"
}

variable "backend_certificate_arn" {
  description = "The ARN of the ACM certificate for the API Gateway"
  type        = string
}

variable "use_bucketav" {
  description = "Use BucketAV to prevent malware to be uploaded in S3 bucket"
  type        = bool
  default     = false
}

variable "bucketav_sns_findings_topic_name" {
  description = "Name of SNS topics where BucketAV publishes findings"
  type        = string
}

variable "enable_transfer_acceleration" {
  type        = bool
  description = "Enable S3 Transfer Acceleration?"
  default     = false
}

variable "lambda_upload_presigned_url_expiration_time_s" {
  description = "Expiration time in seconds for the pre-signed URL generated by the upload Lambda function"
  type        = number
  default     = 300
}

variable "lambda_memory_size_mb" {
  description = "Memory size in MB value for Lambda processing file which allow faster execution"
  type        = number
  default     = 512
}
# END