name: Apply Secrets/Cognito/Backend layers to Staging Env

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - staging

jobs:
  apply-secrets:
    name: Secrets - Apply to ${{ github.event.inputs.environment }} Env
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_app_id: docu-chat-ai
      TF_VAR_environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387836084035:role/githubDocuChatAIManager
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform/layers/secrets
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=docu-chat-ai-app-states" \
            -backend-config="key=secrets/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ github.event.inputs.environment }}-docu-chat-ai-terraform-locks" \
            -backend-config="encrypt=true"

      - name: Terraform Apply
        working-directory: terraform/layers/secrets
        run: |
          terraform apply -auto-approve

  apply-cognito:
    needs: apply-secrets
    name: Cognito - Apply to ${{ github.event.inputs.environment }} Env
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_app_id: docu-chat-ai
      TF_VAR_environment: ${{ github.event.inputs.environment }}
      TF_VAR_callback_urls: '["https://${{ github.event.inputs.environment }}.epic-trip-planner.com"]'
      TF_VAR_logout_urls: '["https://${{ github.event.inputs.environment }}.epic-trip-planner.com"]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387836084035:role/githubDocuChatAIManager
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform/layers/cognito
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=docu-chat-ai-app-states" \
            -backend-config="key=cognito/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ github.event.inputs.environment }}-docu-chat-ai-terraform-locks" \
            -backend-config="encrypt=true"

      - name: Terraform Apply - Cognito Base
        working-directory: terraform/layers/cognito
        run: |
          terraform apply -target="module.cognito_base" -auto-approve

      - name: Terraform Apply - Cognito Clients
        working-directory: terraform/layers/cognito
        run: |
          terraform apply -target="module.cognito_clients" -auto-approve

  apply-backend:
    name: Backend - Apply to ${{ github.event.inputs.environment }} Env
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: apply-cognito
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_environment: ${{ github.event.inputs.environment }}
      TF_VAR_app_id: docu-chat-ai
      TF_VAR_cloudfront_domain_name: ${{ github.event.inputs.environment }}.epic-trip-planner.com
      TF_VAR_api_file_upload_domain_name: ${{ github.event.inputs.environment }}-file-upload-api.epic-trip-planner.com
      TF_VAR_backend_certificate_arn: ${{secrets.BACKEND_CERTIFICATE_ARN}}
      TF_VAR_use_bucketav: false
      TF_VAR_bucket_av_sns_findings_topic_name: ""
      TF_VAR_uploads_bucket_name: docu-chat-ai-file-uploads-bucket-${{ github.event.inputs.environment }}
      TF_VAR_enable_transfer_acceleration: true
      TF_VAR_secret_store_name: ${{secrets.SECRET_STORE_NAME}}
      TF_VAR_notification_email: ${{secrets.ALERT_EMAIL}}
      TF_VAR_route53_zone_name: epic-trip-planner.com
      TF_VAR_alt_cloudfront_domain_name: ${{ github.event.inputs.environment }}.epic-trip-planner.com
      TF_VAR_s3_ingestion_lambda_code_bucket: ${{ secrets.S3_INGESTION_LAMBDA_CODE_BUCKET }}
      TF_VAR_s3_ingestion_lambda_code_key: "${{ github.event.inputs.environment }}/s3-ingestion.zip"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387836084035:role/githubDocuChatAIManager
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform/layers/backend
        run: |
          terraform init \
            -input=false -upgrade \
            -backend-config="bucket=docu-chat-ai-app-states" \
            -backend-config="key=backend/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=eu-central-1" \
            -backend-config="dynamodb_table=${{ github.event.inputs.environment }}-docu-chat-ai-terraform-locks" \
            -backend-config="encrypt=true"

      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Module File Uploader - Build Lambda packages (${{ github.event.inputs.environment }})
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential python3 libvips-dev
          cd terraform/layers/backend/.terraform/modules/file_uploader/terraform/modules/file_uploader/src/lambdas/get_presigned_url
          npm ci --silent --no-audit
          cd ../process_uploaded_file
          npm ci --silent --no-audit

      - name: Backend layer - Build Lambda packages (${{ github.event.inputs.environment }})
        run: |
          cd terraform/layers/backend/src/lambda_functions/get_document_data
          npm ci --silent --no-audit
          cd ../get_file
          npm ci --silent --no-audit
          cd ../list_files
          npm ci --silent --no-audit
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Lambda S3 Bucket for S3 Ingestion Lambda
        run: |
          # Check if bucket exists
          if ! aws s3 ls "s3://$TF_VAR_s3_ingestion_lambda_code_bucket" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "Bucket exists."
          else
            echo "Bucket does not exist. Creating $TF_VAR_s3_ingestion_lambda_code_bucket..."
            aws s3 mb "s3://$TF_VAR_s3_ingestion_lambda_code_bucket" --region ${{ secrets.AWS_REGION }}
          fi

      - name: Build S3 Ingestion Lambda Code
        run: |
          cd terraform/layers/backend/src/lambda_functions/s3_ingestion
          # Install Python dependencies into build folder
          pip install -r requirements.txt -t build/
          # Copy handler file
          cp s3_ingestion.py build/
          # Create ZIP
          cd build
          zip -r ../../lambda_s3_ingestion.zip .
          cd ../../..

      - name: Upload Lambda to S3
        run: |
          aws s3 cp terraform/layers/backend/src/lambda_functions/s3_ingestion/lambda_s3_ingestion.zip \
                    s3://$TF_VAR_s3_ingestion_lambda_code_bucket/$TF_VAR_s3_ingestion_lambda_code_key

      - name: Terraform Apply
        working-directory: terraform/layers/backend
        run: |
          terraform apply -auto-approve